//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SageX3SoapWsTester.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://cai715099:8124/soap-generic/syracuse/collaboration/syracuse/CAdxWebService" +
            "XmlCC")]
        public string SageX3SoapWsTester_CAdxWebServiceXmlCC_CAdxWebServiceXmlCCService {
            get {
                return ((string)(this["SageX3SoapWsTester_CAdxWebServiceXmlCC_CAdxWebServiceXmlCCService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://cai715099:8124/soap-generic/syracuse/collaboration/syracuse/CAdxWebService" +
            "XmlCC")]
        public string SageX3WebServiceClient_CAdxWebServiceXmlCC_CAdxWebServiceXmlCCService {
            get {
                return ((string)(this["SageX3WebServiceClient_CAdxWebServiceXmlCC_CAdxWebServiceXmlCCService"]));
            }
        }
    }
}
